site_name: Lat铆n
site_url: https://moronbandin.github.io/latout
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest

nav:
  - Inicio: index.md
  -  Unidades:
      - Primer Trimestre (1AV): 
          - Unidad 1:
              -  Introducci贸n: UNIDADES/1AV/1/index.md
              -  Texto en Markdown: UNIDADES/1AV/1/textos/1.md
              -  Texto en PDF: UNIDADES/1AV/1/textos/[1]imperium_romanum.pdf
              -  Teor铆a: UNIDADES/1AV/1/teoria/apuntes.md
              -  Vocabulario: UNIDADES/1AV/1/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/1AV/1/teoria/extra/ejercicios.md
          - Unidad 2:
              -  Introducci贸n: UNIDADES/1AV/2/index.md
              -  Texto en Markdown: UNIDADES/1AV/2/textos/2.md
              -  Texto en PDF: UNIDADES/1AV/2/textos/[2]familia_romana.pdf
              -  Teor铆a: UNIDADES/1AV/2/teoria/apuntes.md
              -  Vocabulario: UNIDADES/1AV/2/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/1AV/2/teoria/extra/ejercicios.md
          - Unidad 3:
              -  Introducci贸n: UNIDADES/1AV/3/index.md
              -  Texto en Markdown: UNIDADES/1AV/3/textos/3.md
              -  Texto en PDF: UNIDADES/1AV/3/textos/[3]puer_improbus.pdf
              -  Teor铆a: UNIDADES/1AV/3/teoria/apuntes.md
              -  Vocabulario: UNIDADES/1AV/3/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/1AV/3/teoria/extra/ejercicios.md
          - Unidad 4:
              -  Introducci贸n: UNIDADES/1AV/4/index.md
              -  Texto en Markdown: UNIDADES/1AV/4/textos/4.md
              -  Texto en PDF: UNIDADES/1AV/4/textos/[4]dominus_et_servi.pdf
              -  Teor铆a: UNIDADES/1AV/4/teoria/apuntes.md
              -  Vocabulario: UNIDADES/1AV/4/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/1AV/4/teoria/extra/ejercicios.md
          - Unidad 5:
              -  Introducci贸n: UNIDADES/1AV/5/index.md
              -  Texto en Markdown: UNIDADES/1AV/5/textos/5.md
              -  Texto en PDF: UNIDADES/1AV/5/textos/[5]villa_et_hortus.pdf
              -  Teor铆a: UNIDADES/1AV/5/teoria/apuntes.md
              -  Vocabulario: UNIDADES/1AV/5/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/1AV/5/teoria/extra/ejercicios.md
      - Segundo Trimestre (2AV): 
          - Unidad 6:
              -  Introducci贸n: UNIDADES/2AV/6/index.md
              -  Texto en Markdown: UNIDADES/2AV/6/textos/6.md
              -  Texto en PDF: UNIDADES/2AV/6/textos/[6]via_latina.pdf
              -  Teor铆a: UNIDADES/2AV/6/teoria/apuntes.md
              -  Vocabulario: UNIDADES/2AV/6/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/2AV/6/teoria/extra/ejercicios.md
          - Unidad 7:
              -  Introducci贸n: UNIDADES/2AV/7/index.md
              -  Texto en Markdown: UNIDADES/2AV/7/textos/7.md
              -  Texto en PDF: UNIDADES/2AV/7/textos/[7]puella_et_rosa.pdf
              -  Teor铆a: UNIDADES/2AV/7/teoria/apuntes.md
              -  Vocabulario: UNIDADES/2AV/7/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/2AV/7/teoria/extra/ejercicios.md
          - Unidad 8:
              -  Introducci贸n: UNIDADES/2AV/8/index.md
              -  Texto en Markdown: UNIDADES/2AV/8/textos/8.md
              -  Texto en PDF: UNIDADES/2AV/8/textos/[8]taberna_romana.pdf
              -  Teor铆a: UNIDADES/2AV/8/teoria/apuntes.md
              -  Vocabulario: UNIDADES/2AV/8/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/2AV/8/teoria/extra/ejercicios.md
          - Unidad 9:
              -  Introducci贸n: UNIDADES/2AV/9/index.md
              -  Texto en Markdown: UNIDADES/2AV/9/textos/9.md
              -  Texto en PDF: UNIDADES/2AV/9/textos/[9]pastor_et_oves.pdf
              -  Teor铆a: UNIDADES/2AV/9/teoria/apuntes.md
              -  Vocabulario: UNIDADES/2AV/9/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/2AV/9/teoria/extra/ejercicios.md
          - Unidad 10:
              -  Introducci贸n: UNIDADES/3AV/10/index.md
              -  Texto en Markdown: UNIDADES/3AV/10/textos/10.md
              -  Texto en PDF: UNIDADES/3AV/10/textos/[10]bestiae_et_homines.pdf
              -  Teor铆a: UNIDADES/3AV/10/teoria/apuntes.md
              -  Vocabulario: UNIDADES/3AV/10/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/3AV/10/teoria/extra/ejercicios.md
      - Tercer Trimestre (3AV):
          - Unidad 11:
              -  Introducci贸n: UNIDADES/3AV/11/index.md
              -  Texto en Markdown: UNIDADES/3AV/11/textos/11.md
              -  Texto en PDF: UNIDADES/3AV/11/textos/[11]corpus_humanum.pdf
              -  Teor铆a: UNIDADES/3AV/11/teoria/apuntes.md
              -  Vocabulario: UNIDADES/3AV/11/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/3AV/11/teoria/extra/ejercicios.md
          - Unidad 12:
              -  Introducci贸n: UNIDADES/3AV/12/index.md
              -  Texto en Markdown: UNIDADES/3AV/12/textos/12.md
              -  Texto en PDF: UNIDADES/3AV/12/textos/[12]miles_romanus.pdf
              -  Teor铆a: UNIDADES/3AV/12/teoria/apuntes.md
              -  Vocabulario: UNIDADES/3AV/12/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/3AV/12/teoria/extra/ejercicios.md
          - Unidad 13:
              -  Introducci贸n: UNIDADES/3AV/13/index.md
              -  Texto en Markdown: UNIDADES/3AV/13/textos/13.md
              -  Texto en PDF: UNIDADES/3AV/13/textos/[13]annus_et_menses.pdf
              -  Teor铆a: UNIDADES/3AV/13/teoria/apuntes.md
              -  Vocabulario: UNIDADES/3AV/13/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/3AV/13/teoria/extra/ejercicios.md
          - Unidad 14:
              -  Introducci贸n: UNIDADES/3AV/14/index.md
              -  Texto en Markdown: UNIDADES/3AV/14/textos/14.md
              -  Texto en PDF: UNIDADES/3AV/14/textos/[14]novus_dies.pdf
              -  Teor铆a: UNIDADES/3AV/14/teoria/apuntes.md
              -  Vocabulario: UNIDADES/3AV/14/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/3AV/14/teoria/extra/ejercicios.md
          - Unidad 15:
              -  Introducci贸n: UNIDADES/3AV/15/index.md
              -  Texto en Markdown: UNIDADES/3AV/15/textos/15.md
              -  Texto en PDF: UNIDADES/3AV/15/textos/[15]magister_et_discipuli.pdf
              -  Teor铆a: UNIDADES/3AV/15/teoria/apuntes.md
              -  Vocabulario: UNIDADES/3AV/15/teoria/extra/vocabulario.md
              -  Ejercicios: UNIDADES/3AV/15/teoria/extra/ejercicios.md
  -  Material Extra: UNIDADES/EXTRA/index.md


plugins:
  - search

extra:
  navigation.indexes: false
